[workspace]
members = ["stillsync-cli", "stillsync-core", "stillsync-gui"]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["dipo33"]
description = "Rust service for syncing files to cloud"

